require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ToolBomsController do

  # This should return the minimal set of attributes required to create a valid
  # ToolBom. As you add validations to ToolBom, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "hilt_no" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ToolBomsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tool_boms as @tool_boms" do
      tool_bom = ToolBom.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tool_boms).should eq([tool_bom])
    end
  end

  describe "GET show" do
    it "assigns the requested tool_bom as @tool_bom" do
      tool_bom = ToolBom.create! valid_attributes
      get :show, {:id => tool_bom.to_param}, valid_session
      assigns(:tool_bom).should eq(tool_bom)
    end
  end

  describe "GET new" do
    it "assigns a new tool_bom as @tool_bom" do
      get :new, {}, valid_session
      assigns(:tool_bom).should be_a_new(ToolBom)
    end
  end

  describe "GET edit" do
    it "assigns the requested tool_bom as @tool_bom" do
      tool_bom = ToolBom.create! valid_attributes
      get :edit, {:id => tool_bom.to_param}, valid_session
      assigns(:tool_bom).should eq(tool_bom)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ToolBom" do
        expect {
          post :create, {:tool_bom => valid_attributes}, valid_session
        }.to change(ToolBom, :count).by(1)
      end

      it "assigns a newly created tool_bom as @tool_bom" do
        post :create, {:tool_bom => valid_attributes}, valid_session
        assigns(:tool_bom).should be_a(ToolBom)
        assigns(:tool_bom).should be_persisted
      end

      it "redirects to the created tool_bom" do
        post :create, {:tool_bom => valid_attributes}, valid_session
        response.should redirect_to(ToolBom.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tool_bom as @tool_bom" do
        # Trigger the behavior that occurs when invalid params are submitted
        ToolBom.any_instance.stub(:save).and_return(false)
        post :create, {:tool_bom => { "hilt_no" => "invalid value" }}, valid_session
        assigns(:tool_bom).should be_a_new(ToolBom)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ToolBom.any_instance.stub(:save).and_return(false)
        post :create, {:tool_bom => { "hilt_no" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tool_bom" do
        tool_bom = ToolBom.create! valid_attributes
        # Assuming there are no other tool_boms in the database, this
        # specifies that the ToolBom created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ToolBom.any_instance.should_receive(:update_attributes).with({ "hilt_no" => "MyString" })
        put :update, {:id => tool_bom.to_param, :tool_bom => { "hilt_no" => "MyString" }}, valid_session
      end

      it "assigns the requested tool_bom as @tool_bom" do
        tool_bom = ToolBom.create! valid_attributes
        put :update, {:id => tool_bom.to_param, :tool_bom => valid_attributes}, valid_session
        assigns(:tool_bom).should eq(tool_bom)
      end

      it "redirects to the tool_bom" do
        tool_bom = ToolBom.create! valid_attributes
        put :update, {:id => tool_bom.to_param, :tool_bom => valid_attributes}, valid_session
        response.should redirect_to(tool_bom)
      end
    end

    describe "with invalid params" do
      it "assigns the tool_bom as @tool_bom" do
        tool_bom = ToolBom.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ToolBom.any_instance.stub(:save).and_return(false)
        put :update, {:id => tool_bom.to_param, :tool_bom => { "hilt_no" => "invalid value" }}, valid_session
        assigns(:tool_bom).should eq(tool_bom)
      end

      it "re-renders the 'edit' template" do
        tool_bom = ToolBom.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ToolBom.any_instance.stub(:save).and_return(false)
        put :update, {:id => tool_bom.to_param, :tool_bom => { "hilt_no" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tool_bom" do
      tool_bom = ToolBom.create! valid_attributes
      expect {
        delete :destroy, {:id => tool_bom.to_param}, valid_session
      }.to change(ToolBom, :count).by(-1)
    end

    it "redirects to the tool_boms list" do
      tool_bom = ToolBom.create! valid_attributes
      delete :destroy, {:id => tool_bom.to_param}, valid_session
      response.should redirect_to(tool_boms_url)
    end
  end

end
