require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ToolPartsController do

  # This should return the minimal set of attributes required to create a valid
  # ToolPart. As you add validations to ToolPart, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "model" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ToolPartsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tool_parts as @tool_parts" do
      tool_part = ToolPart.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tool_parts).should eq([tool_part])
    end
  end

  describe "GET show" do
    it "assigns the requested tool_part as @tool_part" do
      tool_part = ToolPart.create! valid_attributes
      get :show, {:id => tool_part.to_param}, valid_session
      assigns(:tool_part).should eq(tool_part)
    end
  end

  describe "GET new" do
    it "assigns a new tool_part as @tool_part" do
      get :new, {}, valid_session
      assigns(:tool_part).should be_a_new(ToolPart)
    end
  end

  describe "GET edit" do
    it "assigns the requested tool_part as @tool_part" do
      tool_part = ToolPart.create! valid_attributes
      get :edit, {:id => tool_part.to_param}, valid_session
      assigns(:tool_part).should eq(tool_part)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ToolPart" do
        expect {
          post :create, {:tool_part => valid_attributes}, valid_session
        }.to change(ToolPart, :count).by(1)
      end

      it "assigns a newly created tool_part as @tool_part" do
        post :create, {:tool_part => valid_attributes}, valid_session
        assigns(:tool_part).should be_a(ToolPart)
        assigns(:tool_part).should be_persisted
      end

      it "redirects to the created tool_part" do
        post :create, {:tool_part => valid_attributes}, valid_session
        response.should redirect_to(ToolPart.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tool_part as @tool_part" do
        # Trigger the behavior that occurs when invalid params are submitted
        ToolPart.any_instance.stub(:save).and_return(false)
        post :create, {:tool_part => { "model" => "invalid value" }}, valid_session
        assigns(:tool_part).should be_a_new(ToolPart)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ToolPart.any_instance.stub(:save).and_return(false)
        post :create, {:tool_part => { "model" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tool_part" do
        tool_part = ToolPart.create! valid_attributes
        # Assuming there are no other tool_parts in the database, this
        # specifies that the ToolPart created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ToolPart.any_instance.should_receive(:update_attributes).with({ "model" => "MyString" })
        put :update, {:id => tool_part.to_param, :tool_part => { "model" => "MyString" }}, valid_session
      end

      it "assigns the requested tool_part as @tool_part" do
        tool_part = ToolPart.create! valid_attributes
        put :update, {:id => tool_part.to_param, :tool_part => valid_attributes}, valid_session
        assigns(:tool_part).should eq(tool_part)
      end

      it "redirects to the tool_part" do
        tool_part = ToolPart.create! valid_attributes
        put :update, {:id => tool_part.to_param, :tool_part => valid_attributes}, valid_session
        response.should redirect_to(tool_part)
      end
    end

    describe "with invalid params" do
      it "assigns the tool_part as @tool_part" do
        tool_part = ToolPart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ToolPart.any_instance.stub(:save).and_return(false)
        put :update, {:id => tool_part.to_param, :tool_part => { "model" => "invalid value" }}, valid_session
        assigns(:tool_part).should eq(tool_part)
      end

      it "re-renders the 'edit' template" do
        tool_part = ToolPart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ToolPart.any_instance.stub(:save).and_return(false)
        put :update, {:id => tool_part.to_param, :tool_part => { "model" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tool_part" do
      tool_part = ToolPart.create! valid_attributes
      expect {
        delete :destroy, {:id => tool_part.to_param}, valid_session
      }.to change(ToolPart, :count).by(-1)
    end

    it "redirects to the tool_parts list" do
      tool_part = ToolPart.create! valid_attributes
      delete :destroy, {:id => tool_part.to_param}, valid_session
      response.should redirect_to(tool_parts_url)
    end
  end

end
