require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TunningDiagramsController do

  # This should return the minimal set of attributes required to create a valid
  # TunningDiagram. As you add validations to TunningDiagram, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "hilt_no" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TunningDiagramsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tunning_diagrams as @tunning_diagrams" do
      tunning_diagram = TunningDiagram.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tunning_diagrams).should eq([tunning_diagram])
    end
  end

  describe "GET show" do
    it "assigns the requested tunning_diagram as @tunning_diagram" do
      tunning_diagram = TunningDiagram.create! valid_attributes
      get :show, {:id => tunning_diagram.to_param}, valid_session
      assigns(:tunning_diagram).should eq(tunning_diagram)
    end
  end

  describe "GET new" do
    it "assigns a new tunning_diagram as @tunning_diagram" do
      get :new, {}, valid_session
      assigns(:tunning_diagram).should be_a_new(TunningDiagram)
    end
  end

  describe "GET edit" do
    it "assigns the requested tunning_diagram as @tunning_diagram" do
      tunning_diagram = TunningDiagram.create! valid_attributes
      get :edit, {:id => tunning_diagram.to_param}, valid_session
      assigns(:tunning_diagram).should eq(tunning_diagram)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TunningDiagram" do
        expect {
          post :create, {:tunning_diagram => valid_attributes}, valid_session
        }.to change(TunningDiagram, :count).by(1)
      end

      it "assigns a newly created tunning_diagram as @tunning_diagram" do
        post :create, {:tunning_diagram => valid_attributes}, valid_session
        assigns(:tunning_diagram).should be_a(TunningDiagram)
        assigns(:tunning_diagram).should be_persisted
      end

      it "redirects to the created tunning_diagram" do
        post :create, {:tunning_diagram => valid_attributes}, valid_session
        response.should redirect_to(TunningDiagram.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tunning_diagram as @tunning_diagram" do
        # Trigger the behavior that occurs when invalid params are submitted
        TunningDiagram.any_instance.stub(:save).and_return(false)
        post :create, {:tunning_diagram => { "hilt_no" => "invalid value" }}, valid_session
        assigns(:tunning_diagram).should be_a_new(TunningDiagram)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TunningDiagram.any_instance.stub(:save).and_return(false)
        post :create, {:tunning_diagram => { "hilt_no" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tunning_diagram" do
        tunning_diagram = TunningDiagram.create! valid_attributes
        # Assuming there are no other tunning_diagrams in the database, this
        # specifies that the TunningDiagram created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TunningDiagram.any_instance.should_receive(:update_attributes).with({ "hilt_no" => "MyString" })
        put :update, {:id => tunning_diagram.to_param, :tunning_diagram => { "hilt_no" => "MyString" }}, valid_session
      end

      it "assigns the requested tunning_diagram as @tunning_diagram" do
        tunning_diagram = TunningDiagram.create! valid_attributes
        put :update, {:id => tunning_diagram.to_param, :tunning_diagram => valid_attributes}, valid_session
        assigns(:tunning_diagram).should eq(tunning_diagram)
      end

      it "redirects to the tunning_diagram" do
        tunning_diagram = TunningDiagram.create! valid_attributes
        put :update, {:id => tunning_diagram.to_param, :tunning_diagram => valid_attributes}, valid_session
        response.should redirect_to(tunning_diagram)
      end
    end

    describe "with invalid params" do
      it "assigns the tunning_diagram as @tunning_diagram" do
        tunning_diagram = TunningDiagram.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TunningDiagram.any_instance.stub(:save).and_return(false)
        put :update, {:id => tunning_diagram.to_param, :tunning_diagram => { "hilt_no" => "invalid value" }}, valid_session
        assigns(:tunning_diagram).should eq(tunning_diagram)
      end

      it "re-renders the 'edit' template" do
        tunning_diagram = TunningDiagram.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TunningDiagram.any_instance.stub(:save).and_return(false)
        put :update, {:id => tunning_diagram.to_param, :tunning_diagram => { "hilt_no" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tunning_diagram" do
      tunning_diagram = TunningDiagram.create! valid_attributes
      expect {
        delete :destroy, {:id => tunning_diagram.to_param}, valid_session
      }.to change(TunningDiagram, :count).by(-1)
    end

    it "redirects to the tunning_diagrams list" do
      tunning_diagram = TunningDiagram.create! valid_attributes
      delete :destroy, {:id => tunning_diagram.to_param}, valid_session
      response.should redirect_to(tunning_diagrams_url)
    end
  end

end
